# Generated by Django 5.2.9 on 2025-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_cleanup_legacy_assesments_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['course', 'type', 'date'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('PROJECT', 'Project'), ('ATTENDANCE', 'Attendance')], default='ATTENDANCE', max_length=20),
        ),
    ]
