# Generated by Django 5.2.9 on 2025-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_faculty_customuser_faculty_member_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(blank=True, help_text='Öğrenci numarası', max_length=32, null=True),
        ),
    ]
